<?php
/**
 * This file is part of megafacturador
 * Copyright (C) 2014-2025 Carlos Garcia Gomez <neorazorx@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace FacturaScripts\Plugins\Megafacturador\Controller;

use FacturaScripts\Core\Base\Controller;
use FacturaScripts\Core\Base\ExportManager;
use FacturaScripts\Core\Tools;
use FacturaScripts\Dinamic\Lib\Email\EmailTools;
use FacturaScripts\Dinamic\Model\Empresa;
use FacturaScripts\Dinamic\Model\FacturaCliente;

/**
 * Controller to send emails for invoices generated by megafacturador
 *
 * @author Carlos Garcia Gomez <neorazorx@gmail.com>
 */
class MegafacturadorEmail extends Controller
{
    /**
     * @var string
     */
    public $tmpFile;

    /**
     * @var int
     */
    public $totalFacturas;

    /**
     * Returns basic page attributes
     *
     * @return array
     */
    public function getPageData(): array
    {
        $data = parent::getPageData();
        $data['menu'] = 'sales';
        $data['title'] = 'Enviar Emails - MegaFacturador';
        $data['icon'] = 'fas fa-envelope';
        return $data;
    }

    /**
     * Runs the controller's private logic
     *
     * @param mixed $response
     * @param mixed $user
     * @param mixed $permissions
     */
    public function privateCore(&$response, $user, $permissions)
    {
        parent::privateCore($response, $user, $permissions);

        $runId = $this->request->get('runid', '');
        $this->tmpFile = sys_get_temp_dir() . '/megafac_' . $runId . '.txt';
        $this->totalFacturas = 0;

        // Count invoices to send
        if (file_exists($this->tmpFile)) {
            $fileContent = file_get_contents($this->tmpFile);
            $facturasIds = array_filter(explode("\n", trim($fileContent)));
            $this->totalFacturas = count($facturasIds);
        }

        // Send emails if requested
        if ($this->request->get('enviar') === 'TRUE') {
            $this->enviarFacturas();
        }
    }

    /**
     * Send emails for all generated invoices
     */
    private function enviarFacturas(): void
    {
        if ($this->permissions->onlyOwnerData) {
            Tools::log()->error('send-invoices-access-denied');
            return;
        }

        if (!file_exists($this->tmpFile)) {
            Tools::log()->error('no-temp-file-found');
            return;
        }

        // Read invoice IDs from temp file
        $fileContent = file_get_contents($this->tmpFile);
        $facturasIds = array_filter(explode("\n", trim($fileContent)));

        if (empty($facturasIds)) {
            Tools::log()->warning('no-invoices-to-send');
            return;
        }

        // Load invoices by their IDs
        $facturaModel = new FacturaCliente();
        $facturas = [];
        foreach ($facturasIds as $id) {
            $factura = $facturaModel->get($id);
            if ($factura) {
                $facturas[] = $factura;
            }
        }

        $enviados = 0;
        $errores = 0;

        foreach ($facturas as $factura) {
            // Get customer email
            if (empty($factura->email)) {
                Tools::log()->warning('invoice-without-email', ['%invoice%' => $factura->codigo]);
                $errores++;
                continue;
            }

            // Send email with invoice PDF attached
            $emailTools = new EmailTools();
            $mail = $emailTools->newMail();
            $mail->addAddress($factura->email, $factura->nombrecliente);

            // Subject
            $empresa = new Empresa();
            if ($empresa->loadFromCode($factura->idempresa)) {
                $mail->Subject = $empresa->nombrecorto . ' - Factura ' . $factura->codigo;
            } else {
                $mail->Subject = 'Factura ' . $factura->codigo;
            }

            // Body
            $mail->msgHTML(
                '<p>Estimado/a <strong>' . $factura->nombrecliente . '</strong>,</p>' .
                '<p>Adjuntamos la factura <strong>' . $factura->codigo . '</strong>.</p>' .
                '<p>Atentamente,<br>' . ($empresa->nombrecorto ?? 'Su empresa') . '</p>'
            );

            // Attach PDF using export manager
            try {
                $exportManager = new ExportManager();
                $exportManager->newDoc('PDF', $factura->modelClassName());
                $exportManager->addModelPage($factura->modelClassName(), $factura->codigo, [], $factura->codigo);

                $pdfPath = $exportManager->getDoc();
                if ($pdfPath && file_exists($pdfPath)) {
                    $mail->addAttachment($pdfPath, $factura->codigo . '.pdf');
                }
            } catch (\Exception $e) {
                Tools::log()->error('pdf-generation-error', ['%error%' => $e->getMessage()]);
            }

            // Send
            if ($mail->send()) {
                $enviados++;
                Tools::log()->info('invoice-email-sent', ['%invoice%' => $factura->codigo, '%email%' => $factura->email]);
            } else {
                $errores++;
                Tools::log()->error('invoice-email-error', ['%invoice%' => $factura->codigo, '%error%' => $mail->ErrorInfo]);
            }

            // Clean up PDF file
            if (isset($pdfPath) && file_exists($pdfPath)) {
                @unlink($pdfPath);
            }
        }

        Tools::log()->notice($enviados . ' emails sent, ' . $errores . ' errors.');

        // Clean up temp file after sending
        @unlink($this->tmpFile);

        // Redirect back to megafacturador
        $this->redirect($this->url() . '?page=Megafacturador');
    }
}
